//
//  ViewController.swift
//  Tip Calculator
//
//  Created by Amani Ngomasele on 11/8/24.
//

import UIKit

class ViewController: UIViewController {
    
    @IBOutlet weak var billAmountLabel: UILabel!
    @IBOutlet weak var customTipPercentLabel: UILabel!
    @IBOutlet weak var customTipPercentSlider: UISlider!
    @IBOutlet weak var tipCustomLabel: UILabel!
    @IBOutlet weak var totalCustomLabel: UILabel!
    @IBOutlet weak var inputTextField: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        //Reinforce that the initial tip percent is 15%
        customTipPercentSlider.value = 15
        
        //Select the TextField so keypad displays when the view loads
        inputTextField.becomeFirstResponder()
    }
    @IBAction func calculateTip(_ sender: Any) {
        
        // Variables to be used in this method or function
        var decimal100: Double = 100.0
        var customPercent: Double = 0.0
        var billAmount: Double = 0.0
        var inputDouble: Double = 0.0
        
        // Get the user input and store it in a variable
        let inputString = inputTextField.text
        
        // Convert the value entered (string) to a double
        inputDouble = Double((inputString! as NSString).floatValue)
        
        // Convert the slider value to a decimal number and store in a variable
        let sliderValue = Int(customTipPercentSlider.value)
        
        // Convert the slider value set by the user to a percent
        customPercent = Double(sliderValue) / decimal100
        
        // Identify who generated the event. Was it the slider?
        if sender is UISlider {
            // The thumb has been moved by the user, so update the label with the new custom percent
            customTipPercentLabel.text = NumberFormatter.localizedString(from: NSNumber(value: customPercent), number: .percent)
        }
        
        // If there is a bill amount, calculate the new tip and total
        if !(inputString?.isEmpty ?? true) {
            // Convert the billAmount to add the decimal point
            billAmount = inputDouble / decimal100
            
            // Check if the event was generated by the TextField
            if sender is UITextField {
                // Update the billAmount with the currency format
                billAmountLabel.text = " " + formatAsCurrency(number: billAmount)
            }
            
            // Calculate and display the tip and the total with currency format
            let customTip = billAmount * customPercent
            tipCustomLabel.text = formatAsCurrency(number: customTip)
            totalCustomLabel.text = formatAsCurrency(number: billAmount + customTip)
        } else {
            // Clear all the labels
            billAmountLabel.text = " "
            customTipPercentLabel.text = NumberFormatter.localizedString(from: NSNumber(value: customPercent), number: .percent)
            tipCustomLabel.text = " "
            totalCustomLabel.text = " "
        }
        
        // Global utility function
        // Convert a numeric value to a localized currency string
        func formatAsCurrency(number: Double) -> String {
            return NumberFormatter.localizedString(from: NSNumber(value: number), number: .currency)
        }
    }
}
